# Generated by Django 4.1.2 on 2022-11-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date',
            new_name='date_naissance',
        ),
    ]
