# Generated by Django 4.1.2 on 2022-11-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_date_client_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
