# Generated by Django 4.1.2 on 2022-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
