# Generated by Django 4.1.2 on 2022-11-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_age_client_adresse_client_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
