# Generated by Django 4.1.2 on 2022-11-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_alter_vehicule_client'),
        ('client', '0005_client_date_enregistrement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
