# Generated by Django 4.1.2 on 2022-11-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherant', '0001_initial'),
        ('vehicule', '0002_alter_vehicule_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='client',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='adherant',
            field=models.ForeignKey(db_column='lucien', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adherant.adherant'),
        ),
    ]
