# Generated by Django 4.1.2 on 2022-11-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherant', '0001_initial'),
        ('sinistre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='date_ex',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='fractionnement',
        ),
        migrations.AddField(
            model_name='sinistre',
            name='date_justification',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='justification',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='adherant',
            field=models.ForeignKey(db_column='sinistré', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adherant.adherant'),
        ),
    ]
