# Generated by Django 4.1.2 on 2022-11-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typeassurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('fractionnement', models.CharField(max_length=200, null=True)),
                ('date_ex', models.DateField()),
                ('numero_assurance', models.IntegerField(null=True)),
                ('type_ass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='typeassurance.typeassurance')),
            ],
        ),
    ]
