# Generated by Django 4.1.2 on 2022-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assure',
            name='fractionnement',
            field=models.CharField(choices=[('mensuel', 'mensuel'), ('annuel', 'annuel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assure',
            name='numero_assurance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
