# Generated by Django 4.1.2 on 2022-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeassurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeassurance',
            name='type_ass',
            field=models.CharField(choices=[('individuel_accident', 'Automobile'), ('individuel_accident', 'vie')], max_length=200, null=True),
        ),
    ]
