# Generated by Django 4.1.2 on 2022-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeassurance', '0002_alter_typeassurance_type_ass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeassurance',
            name='type_ass',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('vie', 'vie')], max_length=200, null=True),
        ),
    ]
